project:
  type: website
  output-dir: docs
website:
  title: "Шаршов Иван"
  navbar:
    left:
      - href: index.qmd
        text: TPage
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

